[2023-08-02 13:54:07,632] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T13:54:06.195305+00:00 [queued]>
[2023-08-02 13:54:07,644] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T13:54:06.195305+00:00 [queued]>
[2023-08-02 13:54:07,644] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 13:54:07,644] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 13:54:07,644] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 13:54:07,673] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 13:54:06.195305+00:00
[2023-08-02 13:54:07,678] {standard_task_runner.py:52} INFO - Started process 2844 to run task
[2023-08-02 13:54:07,681] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-02T13:54:06.195305+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpcqt5cok9', '--error-file', '/tmp/tmpwua91_6j']
[2023-08-02 13:54:07,682] {standard_task_runner.py:80} INFO - Job 397: Subtask load_weather_data
[2023-08-02 13:54:07,740] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T13:54:06.195305+00:00 [running]> on host f57ce474b9bb
[2023-08-02 13:54:07,835] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T13:54:06.195305+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T13:54:06.195305+00:00
[2023-08-02 13:54:14,153] {logging_mixin.py:115} INFO - Error: Could not connect to the endpoint URL: "https://lime-api.s3.amazonaws.com/?list-type=2&prefix=topics%2Fweather_topic%2Fyear%3D2023%2Fmonth%3D08%2Fday%3D01%2F&encoding-type=url"
[2023-08-02 13:54:14,153] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 13:54:14,166] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230802T135406, start_date=20230802T135407, end_date=20230802T135414
[2023-08-02 13:54:14,478] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 13:54:15,417] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
