[2023-08-02 09:17:18,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:17:16.461598+00:00 [queued]>
[2023-08-02 09:17:18,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:17:16.461598+00:00 [queued]>
[2023-08-02 09:17:18,766] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:17:18,767] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 09:17:18,767] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 09:17:18,799] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 09:17:16.461598+00:00
[2023-08-02 09:17:18,804] {standard_task_runner.py:52} INFO - Started process 9599 to run task
[2023-08-02 09:17:18,806] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-02T09:17:16.461598+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpxv79ly6q', '--error-file', '/tmp/tmpsu0j3qtw']
[2023-08-02 09:17:18,807] {standard_task_runner.py:80} INFO - Job 300: Subtask load_weather_data
[2023-08-02 09:17:18,868] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T09:17:16.461598+00:00 [running]> on host 656341a29da6
[2023-08-02 09:17:18,952] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T09:17:16.461598+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T09:17:16.461598+00:00
[2023-08-02 09:17:19,546] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 09:17:19,558] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (13, 11)
[2023-08-02 09:17:19,558] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 09:17:19,559] {logging_mixin.py:115} INFO - Error: name 'key' is not defined
[2023-08-02 09:17:19,562] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 09:17:19,593] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230802T091716, start_date=20230802T091718, end_date=20230802T091719
[2023-08-02 09:17:19,661] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 09:17:19,713] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
