[2023-08-02 08:15:16,854] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T08:15:15.056898+00:00 [queued]>
[2023-08-02 08:15:16,873] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T08:15:15.056898+00:00 [queued]>
[2023-08-02 08:15:16,873] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:15:16,873] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 08:15:16,873] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:15:16,915] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 08:15:15.056898+00:00
[2023-08-02 08:15:16,919] {standard_task_runner.py:52} INFO - Started process 6623 to run task
[2023-08-02 08:15:16,921] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_weather_data', 'manual__2023-08-02T08:15:15.056898+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp48hubh8d', '--error-file', '/tmp/tmpkokyd7ai']
[2023-08-02 08:15:16,922] {standard_task_runner.py:80} INFO - Job 247: Subtask load_weather_data
[2023-08-02 08:15:16,990] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_weather_data manual__2023-08-02T08:15:15.056898+00:00 [running]> on host 656341a29da6
[2023-08-02 08:15:17,115] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T08:15:15.056898+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T08:15:15.056898+00:00
[2023-08-02 08:15:17,633] {logging_mixin.py:115} INFO - Error: name 'context' is not defined
[2023-08-02 08:15:17,636] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 08:15:17,656] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_weather_data, execution_date=20230802T081515, start_date=20230802T081516, end_date=20230802T081517
[2023-08-02 08:15:17,695] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 08:15:17,753] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
