[2023-08-02 07:18:13,423] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T07:18:11.701710+00:00 [queued]>
[2023-08-02 07:18:13,432] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T07:18:11.701710+00:00 [queued]>
[2023-08-02 07:18:13,432] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 07:18:13,432] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 07:18:13,432] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 07:18:13,475] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_weather_data> on 2023-08-02 07:18:11.701710+00:00
[2023-08-02 07:18:13,480] {standard_task_runner.py:52} INFO - Started process 4004 to run task
[2023-08-02 07:18:13,482] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_postgres', 'load_weather_data', 'manual__2023-08-02T07:18:11.701710+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpo31zmksw', '--error-file', '/tmp/tmpjs6vaiii']
[2023-08-02 07:18:13,483] {standard_task_runner.py:80} INFO - Job 242: Subtask load_weather_data
[2023-08-02 07:18:13,550] {task_command.py:370} INFO - Running <TaskInstance: s3_to_postgres.load_weather_data manual__2023-08-02T07:18:11.701710+00:00 [running]> on host 656341a29da6
[2023-08-02 07:18:13,650] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_postgres
AIRFLOW_CTX_TASK_ID=load_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T07:18:11.701710+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T07:18:11.701710+00:00
[2023-08-02 07:18:14,191] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (13, 10)
[2023-08-02 07:18:14,192] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 07:18:20,662] {gbq.py:606} INFO - 13 out of 13 rows loaded.
[2023-08-02 07:18:20,662] {logging_mixin.py:115} INFO - 
✅ Table 2023-08-01 upload on BigQuery! ✅
[2023-08-02 07:18:20,662] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 07:18:21,369] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_postgres, task_id=load_weather_data, execution_date=20230802T071811, start_date=20230802T071813, end_date=20230802T071821
[2023-08-02 07:18:22,732] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 07:18:23,525] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
