[2023-08-02 08:18:38,090] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:18:36.111199+00:00 [queued]>
[2023-08-02 08:18:38,098] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:18:36.111199+00:00 [queued]>
[2023-08-02 08:18:38,098] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:18:38,098] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 08:18:38,098] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:18:38,125] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-08-02 08:18:36.111199+00:00
[2023-08-02 08:18:38,130] {standard_task_runner.py:52} INFO - Started process 6790 to run task
[2023-08-02 08:18:38,132] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_stations_data', 'manual__2023-08-02T08:18:36.111199+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpq1dlmw2v', '--error-file', '/tmp/tmpjqtiymju']
[2023-08-02 08:18:38,133] {standard_task_runner.py:80} INFO - Job 252: Subtask load_stations_data
[2023-08-02 08:18:38,185] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:18:36.111199+00:00 [running]> on host 656341a29da6
[2023-08-02 08:18:38,271] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_stations_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T08:18:36.111199+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T08:18:36.111199+00:00
[2023-08-02 08:18:40,644] {logging_mixin.py:115} INFO - Error: name 'context' is not defined
[2023-08-02 08:18:40,650] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 08:18:40,661] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=load_stations_data, execution_date=20230802T081836, start_date=20230802T081838, end_date=20230802T081840
[2023-08-02 08:18:41,761] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 08:18:41,861] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
