[2023-08-01 22:44:48,738] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:44:43.498127+00:00 [queued]>
[2023-08-01 22:44:48,750] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:44:43.498127+00:00 [queued]>
[2023-08-01 22:44:48,750] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 22:44:48,750] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-01 22:44:48,751] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-01 22:44:48,773] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): weather_data_to_BQ> on 2023-08-01 22:44:43.498127+00:00
[2023-08-01 22:44:48,779] {standard_task_runner.py:52} INFO - Started process 114 to run task
[2023-08-01 22:44:48,782] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 's3_to_BigQuery', 'weather_data_to_BQ', 'manual__2023-08-01T22:44:43.498127+00:00', '--job-id', '196', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpu8j7sco4', '--error-file', '/tmp/tmpbley81rm']
[2023-08-01 22:44:48,783] {standard_task_runner.py:80} INFO - Job 196: Subtask weather_data_to_BQ
[2023-08-01 22:44:48,855] {task_command.py:370} INFO - Running <TaskInstance: s3_to_BigQuery.weather_data_to_BQ manual__2023-08-01T22:44:43.498127+00:00 [running]> on host ab2997d53564
[2023-08-01 22:44:49,001] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=s3_to_BigQuery
AIRFLOW_CTX_TASK_ID=weather_data_to_BQ
AIRFLOW_CTX_EXECUTION_DATE=2023-08-01T22:44:43.498127+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-01T22:44:43.498127+00:00
[2023-08-01 22:44:49,002] {logging_mixin.py:115} INFO - 
 heeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyy
[2023-08-01 22:44:51,442] {logging_mixin.py:115} INFO - Error: Unable to locate credentials
[2023-08-01 22:44:51,443] {python.py:173} INFO - Done. Returned value was: None
[2023-08-01 22:44:51,454] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=s3_to_BigQuery, task_id=weather_data_to_BQ, execution_date=20230801T224443, start_date=20230801T224448, end_date=20230801T224451
[2023-08-01 22:44:51,561] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-01 22:44:51,619] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
