[2023-08-02 08:33:31,366] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:33:29.200863+00:00 [queued]>
[2023-08-02 08:33:31,373] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:33:29.200863+00:00 [queued]>
[2023-08-02 08:33:31,373] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:33:31,373] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 08:33:31,374] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 08:33:31,397] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_stations_data> on 2023-08-02 08:33:29.200863+00:00
[2023-08-02 08:33:31,402] {standard_task_runner.py:52} INFO - Started process 7493 to run task
[2023-08-02 08:33:31,404] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'load_stations_data', 'manual__2023-08-02T08:33:29.200863+00:00', '--job-id', '260', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpa8heeclv', '--error-file', '/tmp/tmpsov_q8sh']
[2023-08-02 08:33:31,405] {standard_task_runner.py:80} INFO - Job 260: Subtask load_stations_data
[2023-08-02 08:33:31,470] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.load_stations_data manual__2023-08-02T08:33:29.200863+00:00 [running]> on host 656341a29da6
[2023-08-02 08:33:31,995] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=load_stations_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T08:33:29.200863+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T08:33:29.200863+00:00
[2023-08-02 08:33:33,966] {logging_mixin.py:115} INFO - 
DataFrame push into xcom.
[2023-08-02 08:33:34,723] {logging_mixin.py:115} INFO - 
DATAFRAME SHAPE : (16003, 8)
[2023-08-02 08:33:34,723] {logging_mixin.py:115} INFO - 
✅ DataFrame created ! ✅
[2023-08-02 08:33:34,728] {python.py:173} INFO - Done. Returned value was:        stationCode  ...               time_period
0            16107  ... 2023-08-01 16:30:00+02:00
1            31104  ... 2023-08-01 16:30:00+02:00
2             9020  ... 2023-08-01 16:30:00+02:00
3            12109  ... 2023-08-01 16:30:00+02:00
4            14111  ... 2023-08-01 16:30:00+02:00
...            ...  ...                       ...
15998        18023  ... 2023-08-02 01:30:00+02:00
15999        18026  ... 2023-08-02 01:30:00+02:00
16000        18024  ... 2023-08-02 01:30:00+02:00
16001        42004  ... 2023-08-02 01:30:00+02:00
16002         8004  ... 2023-08-02 01:30:00+02:00

[16003 rows x 8 columns]
[2023-08-02 08:33:34,911] {xcom.py:585} ERROR - Could not serialize the XCom value into JSON. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config.
[2023-08-02 08:33:34,912] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2392, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 197, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 582, in serialize_value
    return json.dumps(value).encode('UTF-8')
  File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-08-02 08:33:34,921] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=S3_to_BigQuery, task_id=load_stations_data, execution_date=20230802T083329, start_date=20230802T083331, end_date=20230802T083334
[2023-08-02 08:33:35,031] {standard_task_runner.py:97} ERROR - Failed to execute job 260 for task load_stations_data (Object of type DataFrame is not JSON serializable; 7493)
[2023-08-02 08:33:35,068] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-08-02 08:33:35,115] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
