[2023-08-02 10:44:51,461] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T10:44:44.086027+00:00 [queued]>
[2023-08-02 10:44:51,469] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T10:44:44.086027+00:00 [queued]>
[2023-08-02 10:44:51,469] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 10:44:51,469] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2023-08-02 10:44:51,469] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-08-02 10:44:51,503] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): upload_weather_data> on 2023-08-02 10:44:44.086027+00:00
[2023-08-02 10:44:51,507] {standard_task_runner.py:52} INFO - Started process 1832 to run task
[2023-08-02 10:44:51,510] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'S3_to_BigQuery', 'upload_weather_data', 'manual__2023-08-02T10:44:44.086027+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmphp356fh3', '--error-file', '/tmp/tmpq5b629u_']
[2023-08-02 10:44:51,510] {standard_task_runner.py:80} INFO - Job 377: Subtask upload_weather_data
[2023-08-02 10:44:51,569] {task_command.py:370} INFO - Running <TaskInstance: S3_to_BigQuery.upload_weather_data manual__2023-08-02T10:44:44.086027+00:00 [running]> on host f57ce474b9bb
[2023-08-02 10:44:51,683] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=S3_to_BigQuery
AIRFLOW_CTX_TASK_ID=upload_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-08-02T10:44:44.086027+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-08-02T10:44:44.086027+00:00
[2023-08-02 10:44:52,203] {logging_mixin.py:115} INFO - Error: Could not create the table because it already exists. Change the if_exists parameter to 'append' or 'replace' data.
[2023-08-02 10:44:52,203] {python.py:173} INFO - Done. Returned value was: None
[2023-08-02 10:44:52,232] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=S3_to_BigQuery, task_id=upload_weather_data, execution_date=20230802T104444, start_date=20230802T104451, end_date=20230802T104452
[2023-08-02 10:44:52,283] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-08-02 10:44:52,380] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
